[package]
name = "tjlang-diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.12.0"
codespan-reporting = "0.12.0"
miette = "7.6.0"
serde = { version = "1.0.226", features = ["derive"] }
thiserror = "2.0.16"
