[package]
name = "tjlang-tir"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.12.0"
thiserror = "2.0.16"
tjlang-ast = { version = "0.1.0", path = "../tjlang-ast" }
tjlang-diagnostics = { version = "0.1.0", path = "../tjlang-diagnostics" }
