[package]
name = "tjlang-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.12.0"
serde = "1.0.226"
thiserror = "2.0.16"
tjlang-diagnostics = { version = "0.1.0", path = "../tjlang-diagnostics" }
